### ISSUE TITLE
Sync with CPython 3.10

### ISSUE THREAD

**Issue by StevenHsuYL** [python/python-docs-zh-tw#116]
The default [Doc page](https://docs.python.org/zh-tw/3/index.html) already shifted to branch 3.10 recently.
There will be some strings needed to be refreshed here.

Let's sync our branch with cpython 3.10 in future translation work.
Thanks!

**Comment by mattwang44** [comment]
Thanks for the reminder!
I'll manage this after your current PRs (#94, #95, #99, #101) are all merged.

**Comment by mattwang44** [comment]
I've created a branch for 3.10 and made it default branch of this repo. I'll leave this issue opened for another week and make sure no other problem on 3.10.
