### ISSUE TITLE
docs: mention how to search from translated content in README.md

### ISSUE THREAD

**Issue by mattwang44** [python/python-docs-zh-tw#129]
Most translation services (like weblate, transifex, or termsoup) provide the functionality called "translation memories", which suggests the translation based on translated content. However, since we currently do not adopt any of the aforementioned services, it's worth mentioning how to search translated content for a specific word in the project. For example, put a short section mentioning how to use tools like [pogrep](https://github.com/AFPy/pogrep) in README.

The snapshot below shows the sample output of pogrep:

![image](https://user-images.githubusercontent.com/24987826/138810963-7edbb5fe-2c3d-4810-af27-17ce3a8e564f.png)

**Comment by grimmerk** [comment]
A couple of months ago, I noted another translation service, https://gitlocalize.com/. I have not used it and just saw some project use it. Just forward this information to you.

**Comment by mattwang44** [comment]
it's mentioned in the [project wiki](https://github.com/python/python-docs-zh-tw/wiki/%E5%90%84%E7%A8%AE-CLI-%E5%B0%8F%E5%B7%A5%E5%85%B7)
