### ISSUE TITLE
Reduce CI duration

### ISSUE THREAD

**Issue by mattwang44** [python/python-docs-zh-tw#167]
Since we currently run a complete HTML build process in CI, the CI has an unacceptable duration (~16minutes).

Possible solutions:
- Cache CPython directory with [actions/cache](https://github.com/actions/cache).
- Avoid the full building process in CI.

**Comment by cschan1828** [comment]
Now even a single CI workflow takes around 27 minutes.

In my opinion, we can consider checking `.rst` files ~~using `sphinx-build -b gettext`~~ when running CI. On the other hand, CD should be kept as unchanged as it requires full html build.

**Comment by cschan1828** [comment]
After investigating the `Makefile`, I found it is more practical to change the build target to "text". It is not elegant because it occupies extra space for text files. However, it effectively reduces the validation time. In the future we can further optimizations.

**Comment by ezio-melotti** [comment]
Is this issue specific to the zh-tw translations?  Have you checked if other Python translation projects have the same issue, and if/how they fixed it?

**Comment by mattwang44** [comment]
CPython repo has a [Makefile for doc build](https://github.com/python/cpython/blob/d46a42fd8e8915e03cc211ab9163058b6365ab0f/Doc/Makefile), and all translation repos that run doc build with GitHub Action depend on it. It provides different build modes and we currently setup our CI action to run a full doc build with [the `autobuild-dev-html` mode](https://github.com/python/cpython/blob/d46a42fd8e8915e03cc211ab9163058b6365ab0f/Doc/Makefile#L239-L242), which is [the sphinx-native `html` mode](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-b) with [`-E`](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-E) (always rebuild completely) and [`-a`](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-a) (write all output files) options. We've tried out `text` & `html` mode locally and they do much faster than `autobuild-dev-html`, and that's why we believe the `-Ea` option increase the duration and changing the build mode would probably be a decent solution for us.


Here are some metrics from those translation repos that have adopted GitHub Action. French repo also builds with `autobuild-dev-html` but I have no idea why their actions are still blazing fast like the regular `html` mode...

|language|build mode in GitHub Action|translation progress (calculated with [potodo](https://pypi.org/project/potodo/))| GitHub Action appr. duration (min)|
|:-:|:-:|:-:|:-:|
|Spanish|[html](https://github.com/python/python-docs-es/blob/20a4fd3cec759b43ded8408e21dfc612d8e53c24/.github/workflows/main.yml#L53)|95.73% @3.11|4 - 7|
|Simplified Chinese|[html](https://github.com/python/python-docs-zh-cn/blob/4dac60f469b2bfa9c0d2e067f5087fae1d2a059c/.github/scripts/build.sh#L17)|81.16% @3.10|7 - 9|
|Turkish|[html](https://github.com/python/python-docs-tr/blob/786d2f27bbaf1242dba904339960ba41260599a5/Makefile#L66)|1.27% @3.11| 4 - 5|
|Brazilian Portuguese|[html](https://github.com/python/python-docs-pt-br/blob/aa6d19a95e44551b8f1257e22100897b1329f521/Makefile#L68)|43.46% @3.12|5 - 6|
|French|[autobuild-dev-html](https://github.com/python/python-docs-fr/blob/fba25673317c237be4e95709a52203c2564375d2/.github/workflows/tests.yml#L101)|48.14% @3.11|2 - 4|
|Japanese|[html](https://github.com/python/python-docs-ja/blob/9cb7954b12bd0c3b819d7c438453779faa8568b5/.github/workflows/pr_build.yml#L55)|77.09% @3.11| 7 - 9|
|Polish|[html & latex](https://github.com/python/python-docs-pl/blob/f9f9e606688702b79fb47113633a4bfcc5b306e1/.github/workflows/update-lint-and-build.yml#L74)|4.2% @3.12|2 - 3 for html part|
|Ukrainian|[html & latex](https://github.com/python/python-docs-uk/blob/fb0551bbd905a216ede92994d68e7f7b881f2f46/.github/workflows/update-and-build.yml#L50)|84.48% @3.12|3 - 5 for html part|
|Traditional Chinese| autobuild-dev-html|28.34% @3.11|~25|

**Comment by cschan1828** [comment]
I think we can have a simple but effective solution first, then keep working on optimizations.

**Comment by mattwang44** [comment]
@ken71301 
As we mentioned at the sprint, please refer to the discussion above.

My untested thoughts:
- New workflow (e.g. daily) to do the full rebuild (`make all`), and utilize the [cache action](https://github.com/actions/cache) to cache the build artifacts.
- PR CI workflow restores the cached artifacts, and try building for each updated .po files (e.g. `for filename in <find-updated-files>; do make build $$filename; done`) -> expected to be much faster than full build

**Comment by ken71301** [comment]
@mattwang44 
It seems like FR also use html mode now.
https://github.com/python/python-docs-fr/pull/426

**Comment by ken71301** [comment]
In latest sprint Josix and me just tried load of setting and it all seems not effective at all.
So I start believing that cache might be our next option, though I still need to check other's test flow to make sure how we can do it.

**Comment by mattwang44** [comment]
With [this patch](https://github.com/sphinx-doc/sphinx/pull/12995) ([issue](https://github.com/python/docsbuild-scripts/issues/209)) released along with Sphinx 8.1, the build duration in CI has significantly dropped from ~25 mins to ~4 mins 🚀. I believe doc build time would then not be an issue for us. I'll close this issue if no objections in the following days.
