### ISSUE TITLE
One fuzzy string in tutorial/stdlib.po

### ISSUE THREAD

**Issue by adrianliaw** [python/python-docs-zh-tw#23]
There's one fuzzy string inside tutorial/stdlib.po, which is about the email library.  It seems like the text "RFC 2822" has changed to an interpreted text syntax in the source.  See this diff from `git log -L 309,322:tutorial/stdlib.po`

```diff
+++ b/tutorial/stdlib.po
@@ -309,13 +309,14 @@
 #: ../../tutorial/stdlib.rst:319
+#, fuzzy
 msgid ""
 "The :mod:`email` package is a library for managing email messages, including "
-"MIME and other RFC 2822-based message documents. Unlike :mod:`smtplib` and :"
-"mod:`poplib` which actually send and receive messages, the email package has "
-"a complete toolset for building or decoding complex message structures "
-"(including attachments) and for implementing internet encoding and header "
-"protocols."
+"MIME and other :rfc:`2822`-based message documents. Unlike :mod:`smtplib` "
+"and :mod:`poplib` which actually send and receive messages, the email "
+"package has a complete toolset for building or decoding complex message "
+"structures (including attachments) and for implementing internet encoding "
+"and header protocols."
```

**Comment by anubhavsinha98** [comment]
I want to solve this issue!

**Comment by anubhavsinha98** [comment]
So can you explain more about this issue?

**Comment by adrianliaw** [comment]
@anubhavsinha98 Sure, basically this is a "fuzzy entry" issue, meaning that the translation of the entry is out-of-date and should be updated, please see [Fuzzy Entries section in gettext manual](https://www.gnu.org/software/gettext/manual/html_node/Fuzzy-Entries.html) for more information about the fuzzy entries in gettext.  You'll also see the string marked as "Needs work" and coloured in orange.  Please also refer to our readme for more detail about [how to contribute](https://github.com/python/python-docs-zh-tw#id3)

**Comment by ttnppedr** [comment]
@adrianliaw Please assign this issue to me, thanks.
