### ISSUE TITLE
library/functions.po needs review on OpenCC-translated entries translated from zh_CN

### ISSUE THREAD

**Issue by adrianliaw** [python/python-docs-zh-tw#26]
Currently, the library/functions.po contains a bunch of fuzzy entries (shown as orange text and "Needs work" in Poedit), these are the translations borrowed from [zhsj/python-docs-zh-cn](https://github.com/zhsj/python-docs-zh-cn), converted into Traditional Chinese with [OpenCC](https://github.com/BYVoid/OpenCC), these strings need audit to make sure that they deliver the meaning well in Taiwanese Mandarin.

**Comment by Nienzu** [comment]
I will try to help this issue. 
@adrianliaw

**Comment by adrianliaw** [comment]
@Nienzu Thanks for the help! ✨

**Comment by Nienzu** [comment]
This issue has been finished.  Please refer to #29.
