### ISSUE TITLE
Translate tutorial/classes

### ISSUE THREAD

**Issue by josix** [python/python-docs-zh-tw#4]
I will translate tutorial/classes.po

**Comment by adrianliaw** [comment]
@wilson8507 Are you still working on this? If you've finished some parts of this, it's ok to create a pull request with only a few changes (and actually it's better to do so).  Or if you prefer to leave this for someone else to translate, there are definitely lots of people there to help!

**Comment by josix** [comment]
@adrianliaw Sorry about I have not updated the progress yet, and I will create a PR as soon as possible. I'm still working on this issue, however, I'm in a low efficiency due to the busy works in daily 😔. I think I will finish it in one or two weeks. Sorry for your inconvenience and thank for your notification. I will finish it as soon as possible.

**Comment by adrianliaw** [comment]
@wilson8507 No worries! There's no need to rush to complete the translation for the whole document, it's totally fine to leave them for someone else to translate! Actually recently I'm trying out a new policy, which is to translate small parts (say, 3 paragraphs each) and create PRs quickly, review quickly, so the team can move faster but remain the quality. Thus, no need to complete the whole document if you're busy at work!

**Comment by josix** [comment]
@adrianliaw I also agree with this policy! That is great! If so, I think I could continue on this work, and I also list some to-do sections in the PR #52. It will be great if other people can join this work and translate these sections together.

**Comment by josix** [comment]
Hello @StevenHsuYL, I'll try to review this translation and other members in sprint today will review the other chapters so that this project could move faster. We will exchange our reviews after we made the phase one review and try to make the rule of reviewing the translation and make the review process more smoothly.

**Comment by josix** [comment]
Close this issue since it is duplicated with #77
