### ISSUE TITLE
Fix typo tutorial /introduction.po

### ISSUE THREAD

**Issue by AndyChen-ex** [python/python-docs-zh-tw#421]
Line 102 很使用 should change to 可以使用

**Comment by mattwang44** [comment]
Hi @AndyChen-ex 
感謝回報，想請問您會有意願幫忙發 PR 修正這個問題嗎？

**Comment by AndyChen-ex** [comment]
沒問題  麻煩給個權限

**Comment by mattwang44** [comment]
@AndyChen-ex
目前我們不會開放 repo 權限歐，請先 fork 一份再開始開發 & 發 PR（詳細步驟請參考 [repo readme 的**參與翻譯**部分](https://github.com/python/python-docs-zh-tw/blob/3.11/README.rst#id2)），若有遇到任何問題也歡迎直接在這裡發問或至 Sciwork Discord server 的 #pydoc-zhtw channel ([discord.gg/44XheGXhWH](https://discord.gg/44XheGXhWH)) 上與我們討論

**Comment by AndyChen-ex** [comment]
@mattwang44 我發pr了 please code review #423
