### ISSUE TITLE
Translate tutorial/floatingpoint.po

### ISSUE THREAD

**Issue by yichung279** [python/python-docs-zh-tw#43]

**Comment by yichung279** [comment]
How should I translate “a power of two”?
According to wikipedia,it seems to be “2的冪” formally.However,I would like to translate as “以2為底的指數”.It is much easier for beginners.Should I translate formally or beginner-friendly?

**Comment by Nienzu** [comment]
@yichung279,  can you provide the link to the sentence containing "a power of two"?

**Comment by yichung279** [comment]
@Nienzu, Following is the sentence:
`
On most machines today, floats are approximated using a binary fraction with the numerator using the first 53 bits starting with the most significant bit and with the denominator as a power of two. 
`

**Comment by adrianliaw** [comment]
How about keeping the formal term and parenthesise the beginner-friendlier version?

**Comment by mattwang44** [comment]
closed by #89
