### ISSUE TITLE
Fix "fuzzy" mark on `library/smtplib.po`

### ISSUE THREAD

**Issue by cschan1828** [python/python-docs-zh-tw#500]
Fix "fuzzy" mark on `library/smtplib.po`

There is a "fuzzy" mark indicating that a translator's review is required. Once the sentence has been corrected, you can remove the "fuzzy" mark line.

This is a good starting point for newcomers, helping them familiarize themselves with the translation process.

**Comment by mattwang44** [comment]
close it as there isn't any fuzzy entries in library/smtplib.po currently
