### ISSUE TITLE
[Aug 5th Meetup] Translate `library/json.po`

### ISSUE THREAD

**Issue by mattwang44** [python/python-docs-zh-tw#520]
https://github.com/python/python-docs-zh-tw/blob/3.12/library/json.po

e.g. `我要翻譯 #: ../../library/json.rst:2`
```[tasklist]
### Tasks
```

**Comment by husohome** [comment]
小的來翻  這裡
#: ../../library/json.rst:158
msgid ""
"If *check_circular* is false (default: ``True``), then the circular "
"reference check for container types will be skipped and a circular reference "
"will result in a :exc:`RecursionError` (or worse)."
msgstr ""

**Comment by mindihx** [comment]
我要翻譯 `#: ../../library/json.rst:22`

**Comment by kevin1kevin1k** [comment]
我要來翻譯這兩句～
`#: ../../library/json.rst:26`
`#: ../../library/json.rst:29`

**Comment by hcc429** [comment]
我要翻譯 `#: ../../library/json.rst:175 ../../library/json.rst:459`

**Comment by neo-maker-sudo** [comment]
我要翻譯 #: ../../library/json.rst:299, #: ../../library/json.rst:630

**Comment by ken71301** [comment]
我要翻譯 #: ../../library/json.rst:63

**Comment by husohome** [comment]
小的來繼續翻
#: ../../library/json.rst:162
msgid ""
"If *allow_nan* is false (default: ``True``), then it will be a :exc:"
"`ValueError` to serialize out of range :class:`float` values (``nan``, "
"``inf``, ``-inf``) in strict compliance of the JSON specification. If "
"*allow_nan* is true, their JavaScript equivalents (``NaN``, ``Infinity``, ``-"
"Infinity``) will be used."
msgstr ""

**Comment by mindihx** [comment]
接著翻譯 `#: ../../library/json.rst:14`

**Comment by husohome** [comment]
小的繼續翻 `#: ../../library/json.rst:168 ../../library/json.rst:452`

**Comment by husohome** [comment]
小的翻譯了 #: ../../library/json.rst:158 以後 目前到 #: ../../library/json.rst:231 
未來會繼續翻譯  json.po #: ../../library/json.rst:231  以後 直到翻完
