### ISSUE TITLE
[Aug 5th Meetup] Translate `library/datetime.po`

### ISSUE THREAD

**Issue by mattwang44** [python/python-docs-zh-tw#521]
https://github.com/python/python-docs-zh-tw/blob/3.12/library/datetime.po

e.g. `我要翻譯 #: ../../library/datetime.rst:17`

**Comment by xchux** [comment]
我要翻譯 #: ../../library/datetime.rst:2619

**Comment by isabellechiu** [comment]
我要翻譯 #: ../../library/datetime.rst:2483

**Comment by 933yee** [comment]
我要翻譯 #: ../../library/datetime.rst:124

**Comment by estelladai** [comment]
我要翻譯 #: ../../library/datetime.rst:2369

**Comment by oakmegaeddie** [comment]
我要翻譯 #: ../../library/datetime.rst:2501

**Comment by vpwang** [comment]
我要翻譯:#: ../../library/datetime.rst:84

**Comment by Bradley-Tsai** [comment]
我要翻譯 #: ../../library/datetime.rst:196

**Comment by Yang92047111** [comment]
我要翻譯:#: ../../library/datetime.rst:709

**Comment by leeivan1007** [comment]
我要翻譯:#: ../../library/datetime.rst:671

**Comment by pchen11** [comment]
我要翻譯:#: ../../library/datetime.rst:872

**Comment by ccchian** [comment]
我要翻譯:#: ../../library/datetime.rst:157

**Comment by pinerchen** [comment]
用錯帳號登入，pchen11 也是我 XD
我要翻譯:#: ../../library/datetime.rst:872

**Comment by wwangby623** [comment]
我要翻譯：#:../../library/datetime.rst:17

**Comment by avatar220928** [comment]
我要翻譯：../../library/datetime.rst:39

**Comment by mattwang44** [comment]
我要翻譯：../../library/datetime.rst:754

**Comment by vpwang** [comment]
我要翻譯：../../library/datetime.rst:78

**Comment by ccchian** [comment]
我要翻譯：../../library/datetime.rst:179

**Comment by ccchian** [comment]
我要翻譯：../../library/datetime.rst:282
