### ISSUE TITLE
Translation Test

### ISSUE THREAD

**Issue by wwangby623** [python/python-docs-zh-tw#522]

**Comment by mattwang44** [comment]
這是想要翻譯活動指定的 json 或 datetime 嗎？是的話要改成在 #520 或 #521 留言，如果不是的話要麻煩把想要翻譯的範圍寫清楚歐～

**Comment by mattwang44** [comment]
若之後有興趣繼續翻譯的話再麻煩另開 issue 並寫清楚翻譯範圍 🙏🏽
