### ISSUE TITLE
Missing Language headers

### ISSUE THREAD

**Issue by JulienPalard** [python/python-docs-zh-tw#55]
In some files, the Language header is empty:
```
$ git grep '^.Language: \\'
library/asyncio-api-index.po:"Language: \n"
library/asyncio-exceptions.po:"Language: \n"
library/asyncio-future.po:"Language: \n"
library/asyncio-llapi-index.po:"Language: \n"
library/asyncio-platforms.po:"Language: \n"
library/asyncio-policy.po:"Language: \n"
```

Looks like sphinx does not like it:

    reading error: /srv/docsbuild/3.8/locale/zh_TW/LC_MESSAGES/library/asyncio-exceptions.po, expected only letters, got ''

**Comment by adrianliaw** [comment]
Fixed at f4620ba0b31c9f8e7055cfc132465d6089d0cd0c
