### ISSUE TITLE
One fuzzy string in tutorial/datastructures.po

### ISSUE THREAD

**Issue by adrianliaw** [python/python-docs-zh-tw#58]
Simple issue here for first-timers, there's one fuzzy item in [tutorial/datastructures.po](https://github.com/python/python-docs-zh-tw/blob/3.7/tutorial/datastructures.po#L74-L81), you can see the diff from https://github.com/python/python-docs-zh-tw/commit/b6532136e0b74eb3180e056ceb30c2b35e817702#diff-6caf48ff3cc37968163e4a815b4af584, the `ValueError` changed from an inline literal to an rST reference.

**Comment by himanshu007-creator** [comment]
HI i would like to work on this issue ( if not already resolved )

**Comment by mattwang44** [comment]
Already solved in #71.
