### ISSUE TITLE
[Aug 20th PyCon TW Sprints] Translate `library/logging.po`

### ISSUE THREAD

**Issue by weijay0804** [python/python-docs-zh-tw#595]
https://github.com/python/python-docs-zh-tw/blob/3.12/library/logging.po

e.g. `我要翻譯 #: ../../library/logging.rst:16`

**Comment by weijay0804** [comment]
我要翻譯 #: ../../library/logging.rst:16

**Comment by fhsh-YCH** [comment]
我要翻譯 #: ../../library/logging.rst:25

**Comment by kuoJac** [comment]
我要翻譯 #: ../../library/logging.rst:20

**Comment by kuoJac** [comment]
我要翻譯 #: ../../library/logging.rst:21

**Comment by kuoJac** [comment]
我要翻譯 #: ../../library/logging.rst:28

**Comment by fhsh-YCH** [comment]
我要翻譯#: ../../library/logging.rst:2

**Comment by fhsh-YCH** [comment]
我要翻譯#: ../../library/logging.rst:16

**Comment by kuoJac** [comment]
我要翻譯#: ../../library/logging.rst:33

**Comment by kuoJac** [comment]
我要翻譯#: ../../library/logging.rst:41

**Comment by kuoJac** [comment]
我要翻譯#: ../../library/logging.rst:45

**Comment by kuoJac** [comment]
我要翻譯#: ../../library/logging.rst:48

**Comment by Quantum-Spacetime** [comment]
我要翻譯#: ../../library/logging.rst:321
                   ../../library/logging.rst:326
