### ISSUE TITLE
Translate c-api/iterator.rst:17

### ISSUE THREAD

**Issue by bananaiselite** [python/python-docs-zh-tw#620]
Translate c-api/iterator.rst:17

**Comment by mattwang44** [comment]
提醒一下，通常我們是以文件為單位來開 issue（例如 c-api/iterator 就開一個 issue），但可以拆分成多個 PR 來完成（參考 #466）。
你目前還在熟悉這個流程的話，像這樣開一個小範圍的 issue 是沒關係的，不過希望可以慢慢進步到上述這樣XD

**Comment by mattwang44** [comment]
resolved by #621
