### ISSUE TITLE
How to translate "list" and "tuple"

### ISSUE THREAD

**Issue by adrianliaw** [python/python-docs-zh-tw#64]
Marr 提出了一個[翻譯「List」和「Tuple」的觀點](https://medium.com/@l34marr/list-tuple-translation-872c3d449887)，我認同「串列」和「值組」這兩個翻譯，沒什麼問題的話可以加入 glossary 裡。

**Comment by StevenHsuYL** [comment]
我之後也會使用「值組」作為 tuple 的翻譯。
我目前正在處理 glossary.po。

**Comment by scan33scan33** [comment]
您好 我最近在審定一本書，也在想tuple中文要如何翻譯。
看到這個thread。
想請問「值組」是你們建議的翻譯嗎？

**Comment by StevenHsuYL** [comment]
在市面上或學術界沒有共通的翻譯的情況下，我覺得在此訂下初步的共識並持續推廣，是沒有問題的。
我認同 @adrianliaw 提出的「值組」的翻譯，在 glossary 的翻譯草稿中，也會使用此翻譯。
也希望我們能逐步建立繁體中文的共用術語，使國內讀者有共同的溝通詞彙。

**Comment by scan33scan33** [comment]
好唷，我其實也覺得「值組」可以。
如果有任何改變，可以再update這個issue。

BTW, 我一般來講都是看這個: https://terms.naer.edu.tw/search/?q=%22tuple%22&field=ti&num=50  去查可能翻譯。

感謝您

**Comment by StevenHsuYL** [comment]
我在翻譯時，第一優先也是參考教育部辭典。但不太確定時，我會使用 google 稍微瀏覽繁體中文學術網頁常用的翻譯，以及繁體中文 wiki 是否與教育部辭典一致，如果翻譯有差異，可能還會參考 Microsoft Docs 中文版 ( https://docs.microsoft.com/zh-tw/ )，最後綜合這些結果來做出最後的決定。

不過我覺得最好的方法，還是大家在這邊互相討論產生共識，這樣未來有翻譯疑義時也可以回溯討論串並提供建議。

謝謝！
