### ISSUE TITLE
[Nov. 2023 Sprint] Translate `library/string.po`

### ISSUE THREAD

**Issue by rockleona** [python/python-docs-zh-tw#709]
### 我是範例
我要翻譯 `../../library/string.rst:2 到 ../../library/string.rst:19`

**Comment by ken71301** [comment]
發布PR時請對 branch "event-1125" 發布
![image](https://github.com/python/python-docs-zh-tw/assets/27850801/ea93e37d-2c67-4738-b9df-3d08a8d567fc)

**Comment by JustinBear99** [comment]
我要翻譯 `../../library/string.rst:305` 到 `../../library/string.rst:324`

**Comment by heyimkaijoe** [comment]
我要翻譯：
- `../../library/string.rst:38` 到 `../../library/string.rst:81`
- `../../library/string.rst:420` 到 `../../library/string.rst:430`
- `../../library/string.rst:889` 到 `../../library/string.rst:898`
- `../../library/string.rst:910`

**Comment by Yanni0923** [comment]
我要翻譯 `../../library/string.rst:265` 到 `../../library/string.rst:283`

**Comment by proudofsimin** [comment]
Hi All, I'd like to translate ../../library/string.rst:777 to ../../library/string.rst:786
Thanks

**Comment by hector-chin** [comment]
我要翻譯 `../../library/string.rst:595` 到 `../../library/string.rst:702`

**Comment by 7553yn** [comment]
../../library/string.rst:434 to ../../library/string.rst:453

**Comment by heyimkaijoe** [comment]
翻譯：
- `../../library/string.rst:889` 到 `../../library/string.rst:898`
- `../../library/string.rst:910`

**Comment by ShamrockLee** [comment]
我要翻譯 `../../library/string.rst:94`

**Comment by cschan1828** [comment]
`library/string.rst:792` ~ `library/string.rst:840`

**Comment by Yanni0923** [comment]
我要翻譯 
- `../../library/string.rst:344`
- `../../library/string.rst:347`
- `../../library/string.rst:356`
- `../../library/string.rst:360`

**Comment by mattwang44** [comment]
closed by #731
