### ISSUE TITLE
Translate `library/string.po`

### ISSUE THREAD

**Issue by tso1158687** [python/python-docs-zh-tw#737]
Translate

- `rst:26`
- `rst:38`
- `rst:44`
- `rst:49`
- `rst:59`
- `rst:64`
- `rst:71`
- `rst:79`

**Comment by marychiou** [comment]
Translate rst:81, rst:98

**Comment by rockleona** [comment]
@tso1158687 這邊這個 issue 先前已經解決了，我先關閉了喔

@marychiou 今天 sprint 有翻譯這邊，也可以先不用開 issue ，若要繼續翻譯請繼續開新的 issue
