### ISSUE TITLE
active code 翻譯有誤

### ISSUE THREAD

**Issue by xchux** [python/python-docs-zh-tw#798]
[active code](https://github.com/python/python-docs-zh-tw/blob/cbb75563c72eed9b3ca0268555a65e4def8fdcaf/faq/programming.po#L3320)

此處的 active 應為活躍 / 激活 ... ，而非活動

**Comment by mattwang44** [comment]
第 3318 行有標 `#, fuzzy` 代表仍須人工審核、不會顯示在正式文件頁面上

**Comment by xchux** [comment]
了解，感謝
