### ISSUE TITLE
[March 10th Meetup] Translate `library/logging.po`

### ISSUE THREAD

**Issue by rockleona** [python/python-docs-zh-tw#837]
章節：
- [ ] - [Logger Objects](https://docs.python.org/3/library/logging.html#logger-objects)
- [ ] - [Logging Levels](https://docs.python.org/3/library/logging.html#logging-levels)
- [ ] - [Handler Objects](https://docs.python.org/3/library/logging.html#handler-objects)
- [ ] - [Formatter Objects](https://docs.python.org/3/library/logging.html#formatter-objects)
- [ ] - [Filter Objects](https://docs.python.org/3/library/logging.html#filter-objects)
- [ ] - [LogRecord Objects](https://docs.python.org/3/library/logging.html#logrecord-objects)
- [ ] - [LogRecord attributes](https://docs.python.org/3/library/logging.html#logrecord-attributes)
- [ ] - [LoggerAdapter Objects](https://docs.python.org/3/library/logging.html#loggeradapter-objects)
- [ ] - [Thread Safety](https://docs.python.org/3/library/logging.html#thread-safety)
- [ ] - [Module-Level Functions](https://docs.python.org/3/library/logging.html#module-level-functions)
- [ ] - [Module-Level Attributes](https://docs.python.org/3/library/logging.html#module-level-attributes)
- [ ] - [Integration with the warnings module](https://docs.python.org/3/library/logging.html#integration-with-the-warnings-module)

**Comment by rockleona** [comment]
我要翻譯 `library/logging.rst:33`

**Comment by rockleona** [comment]
我要翻譯 `library/logging.rst:41`

**Comment by dl-jack-123** [comment]
我要翻譯 `library/logging.rst:287`

**Comment by nicehorse06** [comment]
我要翻譯 `library/logging.rst:934`

**Comment by Ah-Siao** [comment]
我要翻譯library/logging.rst:82

**Comment by JoycePan810** [comment]
我要翻譯 library/logging.rst:53

**Comment by wcchang1115** [comment]
我要翻譯 `library/logging.rst:118`

**Comment by kyomind** [comment]
我要翻譯`library/logging.rst:100`

**Comment by BK-ni** [comment]
我要翻譯 /library/logging.rst:321

**Comment by viciao** [comment]
我要翻譯library/logging.rst:1125

**Comment by BK-ni** [comment]
我要翻譯 library/logging.rst:340

**Comment by wolke1007** [comment]
我要翻譯 library/logging.rst:1526

**Comment by seal0112** [comment]
我要翻譯 library/logging.rst:193

**Comment by nicehorse06** [comment]
我要翻譯 `library/logging.rst:0 library/logging.rst:964`

**Comment by nicehorse06** [comment]
我要翻譯 

`#: ../../library/logging.rst:917 ../../library/logging.rst:931`
`#: ../../library/logging.rst:959 ../../library/logging.rst:977`

**Comment by seal0112** [comment]
我要翻譯 library/logging.rst:187

**Comment by mattwang44** [comment]
close it as the event has ended (for a while)
