### ISSUE TITLE
[疑問] 該翻譯計畫與https://docs.python.org/的相關性

### ISSUE THREAD

**Issue by heegreis** [python/python-docs-zh-tw#86]
在 https://docs.python.org/ 的 zh-tw 語系大部分都是 zh-ch 的內容，
在 https://docs.python.org/zh-tw/3/bugs.html 中的翻譯 issue 也是導向 https://github.com/python/python-docs-zh-cn/issues，
雖然因而找到此 repo: python/python-docs-zh-tw，但翻譯成果 https://python-doc-tw.github.io/ 的頁面語系選擇中沒有zh-tw，而內容卻是正在翻譯成中文的成果。

請問zh-tw的翻譯成果是有機會更新至 https://docs.python.org/zh-tw/3/ 中的嗎?

**Comment by StevenHsuYL** [comment]
有的，流程是這樣：
大家翻譯完之後，新增PR，主持人 @adrianliaw 會幫忙 review
review之後，如果修改完成，PR就會被merge，然後過幾天出現在官方網頁中。

這邊會遇到的小小困難是，主持人工作有點忙，所以最近 review 比較慢...
前幾個月照這個流程走，是有完成一些新的成果的。
#72 -> https://docs.python.org/zh-tw/3/tutorial/modules.html

**Comment by mattwang44** [comment]
我來補充一下我所知道的東西（可能有少許錯誤XD），如果沒其他疑問的話就要把這個 issue close 囉

> 翻譯成果 python-doc-tw.github.io 的頁面語系選擇中沒有zh-tw...

因為 [PEP 545](https://www.python.org/dev/peps/pep-0545/#add-translation-to-the-language-switcher) 明定要將某翻譯版本釋出的最低條件是要完成 `bugs`, ` library/functions` 和 `tutorial` 相關的所有翻譯，所以在正體中文翻譯計畫初期，[翻譯大多是在 transifex 上進行](https://github.com/python-doc-tw/python-docs-zh-tw/wiki/How-to-translate-(on-Transifex))，翻譯成果是拉到 [python-doc-tw](https://github.com/python-doc-tw) 這個 organization 裡面。[2018 年滿足前述釋出條件、搬到目前所用的這個在 python organization 底下的 repo](https://github.com/python-doc-tw/python-docs-zh-tw/issues/18)，翻譯流程也棄用 transifex 改走 GitHub 協作方式（review 較嚴謹、翻譯品質相對高），而展示翻譯成果的 GitHub page 後來也改到 `python.github.io/python-docs-zh-tw`（`python-doc-tw.github.io` 已棄用，README 已修正）。


> 在 docs.python.org 的 zh-tw 語系大部分都是 zh-ch 的內容

`docs.python.org` 目前是透過 [python/docsbuild-scripts](https://github.com/python/docsbuild-scripts) 去將個翻譯 repo 將翻譯成果拉下來再 build 出來的，而目前 fallback 設定是 _繁體中文沒翻譯的地方是以簡體中文呈現、繁體與簡體中文都沒翻譯的地方是以英文原文呈現_，而正體中文翻譯進度 (4%) 落後簡體中文 (70%) 許多，所以才會看到 zh_TW 頁面內容大多還是簡體中文。

在今年七月的 sprint 討論中，我們的翻譯志工大多希望正體中文沒翻譯到的地方能夠直接 fallback 成英文原文，但我 survey 了一下之後並沒有找到哪裡可以更改這個設定。最近我會再跟大家確認一下是否真的想更改，並視需求詢問 python/docsbuild-scripts 維護者的幫助。


> 在 docs.python.org/zh-tw/3/bugs.html 中的翻譯 issue 也是導向 https://github.com/python/python-docs-zh-cn/issues

在 #93 merged 之後，這個問題已經修正了。

**Comment by heegreis** [comment]
感謝解答
