### ISSUE TITLE
Translate `library/itertools.po`

### ISSUE THREAD

**Issue by kyomind** [python/python-docs-zh-tw#870]
本 po 尚有 89 條待翻，預計分成 3-5 個 pr，待規劃

已查看過所有 issue，確認沒有重工（如果有麻煩提醒）
```[tasklist]
### Tasks
- [ ] 一、itertools 模組介紹與常用迭代器（第 0-410 行）
```

**Comment by ken71301** [comment]
@mattwang44 我能接手嗎 :D

**Comment by mattwang44** [comment]
@kyomind 目前有開始翻譯了嗎？還沒的話我就要 assign 給 Payon 囉

**Comment by kyomind** [comment]
@mattwang44 好，我只試譯了一些而已，真是抱歉
@ken71301 ok 的，可全部接手，請便~🫡

**Comment by mattwang44** [comment]
@kyomind 沒關係的不必抱歉，有心力的話之後可以再嘗試其他篇，感謝~
