### ISSUE TITLE
Bug 回報: MakeFile build  單一檔案(根目錄檔案)問題

### ISSUE THREAD

**Issue by Mayavi345** [python/python-docs-zh-tw#912]
目前根據@timmy0123  #910 的範例進行測試build 單一的根目錄檔案 glossary.po。
如下:

`    VERSION=3.12 make build glossary.po
`
發現網頁glossary.htm 是無法正常更新的。

但測試其他library 裡面檔案 (threading.po)，更新是正常的。

需要進一步驗證該功能的完整性。

* 有問題的檔案
![image](https://github.com/python/python-docs-zh-tw/assets/51351718/3f74f37e-ed91-4d25-96f8-ab355441afeb)

* 可以的檔案
![image](https://github.com/python/python-docs-zh-tw/assets/51351718/c1ea33e2-d1f5-4cab-93dc-a3406711d471)

**Comment by mattwang44** [comment]
Hi @Mayavi345 
#913 應該有解掉這個問題，能麻煩你試試看嗎？

**Comment by Mayavi345** [comment]
@mattwang44 Hi Matt
經過測試，目前看起來"根目錄" 和 "library"中的檔案，目前都可以正常build了
![image](https://github.com/python/python-docs-zh-tw/assets/51351718/7a7cd3de-9b12-4144-9a49-a5796e438b9f)

![image](https://github.com/python/python-docs-zh-tw/assets/51351718/0b88c6ad-aead-45bc-bc89-87dcf3e25b0a)
