### ISSUE TITLE
徵求新的 coordinator

### ISSUE THREAD

**Issue by adrianliaw** [python/python-docs-zh-tw#98]
我也許有在 Telegram 上以及口頭上提及過幾次，不過開一個 issue 應該會比較明確一點。

我想要徵求新的 coordinator，而我自己則會卸下 coordinator 的職位。這並不代表我會完全不再貢獻翻譯（未來還是能繼續以翻譯或是 review 的形式貢獻），但我不想再繼續擔任主要的窗口以及維護者。

主要的原因是我自己在五月初時經歷了一段精神崩潰，而目前還在慢慢的恢復當中，但還不到能夠在工作之餘有效率的組織事務以及思考的狀態。崩潰和這個專案沒有關係，不過我需要一些時間照顧自己的心理健康，而維護或是繼續推進這個專案都會增加額外的負擔（即使並沒有真的很多事情）。

Coordinator 的職責請見 [PEP 545](https://www.python.org/dev/peps/pep-0545/#language-team)，如果您有興趣接手的話，歡迎在這個 issue 底下留言或是透過 adrianliaw2000 at gmail dot com 聯繫我 🙂

**Comment by Eandalf** [comment]
Hi,

請問 coordinator 主要需要組織什麼事物呢？有包含整個服務架構的維護嗎？

**Comment by adrianliaw** [comment]
@Eandalf coordinator 其實就是維護者 / maintainer，所以最主要的職責就是維護這個 repository，並且有權決定翻譯專案的運作方式（工具、審核、issue、團隊、進度，CI、以及統一翻譯用詞等等），且 coordinotar 擁有 python-docs-zh-tw 的 admin 權限。我在擔任 coordinator 時也同時擔任 reviewer，也就是要校正翻譯（並且我自己不做任何翻譯），但是新的 coordinator 可以決定要怎麼 review、要不要有更多 reviewer、還是直接不 review、轉移到其他工具如 Transifex 等等，coordinator 都有完全的決定權。

另外，coordinator 也是 Python core dev 對繁體中文翻譯的主要窗口，所以如果 core dev 在 build docs.python.org 的時候因為某個翻譯出問題的話，他們會在該翻譯的 repo 上開 issue，而那些必須優先處理。另一部分就是持續關注 Doc-SIG mailing list [1]，如果 core dev 那邊針對文件以及翻譯有什麼討論或是有宣布事項，都會發布在該 mailing list 上（但是關於翻譯「內容本身」的問題以及討論則不會在該 mailing list 上）。

Coordinator 必須熟悉 PEP 545 [2]，這個 PEP 詳細說明了 Python 文件翻譯的運作方式（從 Python core dev 的角度看，所以是 i18n 的角度；而不是從我們譯者、 l10n 的角度看）。

希望這樣有解釋到～

[1] https://mail.python.org/pipermail/doc-sig/
[2] https://www.python.org/dev/peps/pep-0545/

**Comment by Eandalf** [comment]
> @Eandalf coordinator 其實就是維護者 / maintainer，所以最主要的職責就是維護這個 repository，並且有權決定翻譯專案的運作方式（工具、審核、issue、團隊、進度，CI、以及統一翻譯用詞等等），且 coordinotar 擁有 python-docs-zh-tw 的 admin 權限。我在擔任 coordinator 時也同時擔任 reviewer，也就是要校正翻譯（並且我自己不做任何翻譯），但是新的 coordinator 可以決定要怎麼 review、要不要有更多 reviewer、還是直接不 review、轉移到其他工具如 Transifex 等等，coordinator 都有完全的決定權。
> 
> 另外，coordinator 也是 Python core dev 對繁體中文翻譯的主要窗口，所以如果 core dev 在 build docs.python.org 的時候因為某個翻譯出問題的話，他們會在該翻譯的 repo 上開 issue，而那些必須優先處理。另一部分就是持續關注 Doc-SIG mailing list [1]，如果 core dev 那邊針對文件以及翻譯有什麼討論或是有宣布事項，都會發布在該 mailing list 上（但是關於翻譯「內容本身」的問題以及討論則不會在該 mailing list 上）。
> 
> Coordinator 必須熟悉 PEP 545 [2]，這個 PEP 詳細說明了 Python 文件翻譯的運作方式（從 Python core dev 的角度看，所以是 i18n 的角度；而不是從我們譯者、 l10n 的角度看）。
> 
> 希望這樣有解釋到～
> 
> [1] https://mail.python.org/pipermail/doc-sig/
> [2] https://www.python.org/dev/peps/pep-0545/

感謝這麼詳細的回覆，我可能比較適合先從 contributor 做起，畢竟之前沒有撰寫官方文件的經驗。

**Comment by mattwang44** [comment]
Hi @adrianliaw,

我希望能夠加入幫忙 review，成為 reviewer 有需要你幫忙開什麼權限嗎？還是直接找 PR assign 給自己就好？

**Comment by adrianliaw** [comment]
@mattwang44 這個就該由新的 coordinator 決定要怎麼建立 reviewer 的制度囉 :)

**Comment by josix** [comment]
Hello @adrianliaw, 非常感謝 adrian 一直以來的維護🙇🏻‍♂️  想請問在暫時還未決定出新的 coordinator 人選時，我們仍會進行 review 和一些 automation 的開發（可參閱[此筆記](https://hackmd.io/@sciwork/HyHIACNeK)），有關 assign review 或是 merge request 等行為的操作權限，這部分的權限是還在你那邊嗎？另外若還不是 coordinator 的人員可以先取得相關的權限嗎，比較方便這邊可以進行下去

**Comment by yungyuc** [comment]
Additional referential information in the minutes from the sprint yesterday: https://hackmd.io/@sciwork/HyHIACNeK

**Comment by adrianliaw** [comment]
@josix 我根本沒有維護 🤫

權限是在我這裡沒錯，我也可以給予其他人員相關權限，目前我想應該需要給予某些人 maintainer 或 write 權限吧？

另外，我想多說一下，我主要會不太想在有新的 coordinator 之前給予（至少 write 的）權限且遲遲不做這件事的原因，是我不希望之後在有新的東西 push 上來之後，如果官方的 build 因為我們的翻譯而炸掉（e.g. rST 語法錯誤），我仍然是 Python core dev 對接的窗口。當然我知道 CI 那部分的工作也是為了避免這類型的事情發生，而且本來就很少發生（但發生過），所以我是覺得沒有太大的問題，但還是想說一下 :)

然後我不太確定如果可以有多個 coordinator 的話，會不會讓新的 coordinator 們壓力比較小，也比較容易有願意接任的志願者（們）？如果是的話，我可以幫忙問問看可不可以有多個 coordinator。

**Comment by yungyuc** [comment]
我們也可以在不改變 coordinator 設定的狀況下先運作一陣子，再決定讓誰接 coordinator，或者是幾位。中譯團隊過去的活動不太多。這種狀況下大家不容易決定下一步該怎麼作。以社群模式合作的話，確保大家有共識還是最重要的事吧。

**Comment by adrianliaw** [comment]
@yungyuc 了解。總之就請你們再告訴我哪些人志願擔任 reviewer 或是負責 automation 的開發，我再開權限。

**Comment by josix** [comment]
沒問題我想可以先依照 @adrianliaw 目前覺得可以給予的權限先交給需要的人，目前依照 sprint 筆記上列的 reviewer 有 @mattwang44, @setmao, @yuyanghh, @tomatoprinx, @josix，及負責 automation 的人有 @mattwang44

另外可能也需要幫忙詢問能不能夠多位 coordinator，麻煩 @adrianliaw  了🙏

**Comment by adrianliaw** [comment]
@josix 我已經幫上面這幾位開 Triage 權限囉，請你們幫我看一下你們能不能 review PR、close PR、管理 issue、加 tag 等等。我目前還沒有開 write 的權限，所以應該是還沒辦法 merge。目前 PR 在核准之後請 tag 我一下然後我再 merge（我需要知道一下 repo 上有哪些動作XD），過一段時間之後我會再開 write 權限。

然後我在 Doc-SIG 上面問了可不可以有多個 coordinator，等待回覆中：https://mail.python.org/pipermail/doc-sig/2021-August/004245.html

**Comment by mattwang44** [comment]
@adrianliaw 我想要接下 coordinator，如果有其他人有意願的話也可以一同擔任這個職位！

**Comment by josix** [comment]
我也可以幫忙 coordinator 的事務 🙏

**Comment by adrianliaw** [comment]
太棒了！我沒理解錯的話，應該是兩位一起接下 coordinator 對吧？（co-coordinators? 🙃 ）

我這幾天公司特別忙，這禮拜有空的時候（也有可能是週末）會再仔細看一下有什麼交接的事情要處理～

**Comment by adrianliaw** [comment]
感謝 @mattwang44 以及 @josix 接下 coordinator 的位子，這個 issue 終於可以關掉了！

**Comment by mattwang44** [comment]
感謝 Adrian！建立 3.10 branch (#116) 的時候我再把 README 裡面的 coordinator 改掉
